In [1]:
import numpy as np
import copy
from sudokusolver import SudokuSolver

In [2]:
# Create 10 x 10 matrix so non programming user can fill the input with 1 based index
sudoku = np.zeros((10, 10), dtype=int)

In [3]:
sudoku[1, []] = []
sudoku[2, []] = []
sudoku[3, []] = []
sudoku[4, []] = []
sudoku[5, []] = []
sudoku[6, []] = []
sudoku[7, []] = []
sudoku[8, []] = []
sudoku[9, []] = []

# # Hard 1
# sudoku[1, [2, 4, 5, 6]] = [8, 5, 6, 4]
# sudoku[2, [3, 9]] = [9, 6]
# sudoku[3, [2, 3, 6, 8]] = [5, 4, 9, 2]
# sudoku[4, [5, 6, 9]] = [5, 8, 3]
# sudoku[5, [4, 6]] = [4, 2]
# sudoku[6, [1, 4, 5]] = [4, 7, 9]
# sudoku[7, [2, 4, 7, 8]] = [3, 9, 8, 7]
# sudoku[8, [1, 7]] = [9, 2]
# sudoku[9, [4, 5, 6, 8]] = [2, 8, 6, 9]

# # Hard 2
# sudoku[1, [5, 7, 8]] = [3, 4, 9]
# sudoku[2, [1, 2, 4, 6, 8, 9]] = [3, 5, 4, 1, 2, 8]
# sudoku[3, [3, 4, 5, 6, 8]] = [9, 6, 2, 5, 3]
# sudoku[4, [2, 3, 5, 6, 7, 8, 9]] = [9, 8, 5, 4, 3, 6, 7]
# sudoku[5, [3, 4, 6]] = [3, 9, 6]
# sudoku[6, [1, 2, 3]] = [6, 7, 1]
# sudoku[7, [7, 9]] = [1, 3]
# sudoku[8, [1, 5, 6, 8, 9]] = [7, 1, 8, 4, 9]
# sudoku[9, [1, 2, 8, 9]] = [9, 1, 8, 6]

# # Expert 1
# sudoku[1, [8]] = [5]
# sudoku[2, [1]] = [3]
# sudoku[3, [2, 3, 4]] = [7, 2, 9]
# sudoku[4, [7, 8, 9]] = [1, 7, 8]
# sudoku[5, [1, 5, 7, 9]] = [8, 6, 3, 2]
# sudoku[6, [1, 5]] = [1, 2]
# sudoku[7, [5, 6, 9]] = [1, 3, 6]
# sudoku[8, [2, 4, 8]] = [5, 4, 9]
# sudoku[9, [3, 6]] = [6, 7]

# Expert 2
sudoku[1, [4, 5]] = [1, 7]
sudoku[2, [7]] = [7]
sudoku[3, [3, 5, 9]] = [3, 5, 6]
sudoku[4, [1, 3, 7]] = [8, 6, 9]
sudoku[5, [6, 9]] = [9, 1]
sudoku[6, [2, 6]] = [2, 8]
sudoku[7, [1, 3, 4, 7]] = [5, 2, 9, 8]
sudoku[8, [2, 3]] = [4, 1]
sudoku[9, [2, 6, 7]] = [6, 4, 3]

In [4]:
# Truncate oth elements to make the matrix back to zero based index
sudoku = sudoku[1:, 1:]

In [5]:
sudoku

array([[0, 0, 0, 1, 7, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 3, 0, 5, 0, 0, 0, 6],
       [8, 0, 6, 0, 0, 0, 9, 0, 0],
       [0, 0, 0, 0, 0, 9, 0, 0, 1],
       [0, 2, 0, 0, 0, 8, 0, 0, 0],
       [5, 0, 2, 9, 0, 0, 8, 0, 0],
       [0, 4, 1, 0, 0, 0, 0, 0, 0],
       [0, 6, 0, 0, 0, 4, 3, 0, 0]])

In [6]:
mysolver = SudokuSolver(sudoku)
mysolver.solveit()

[[0 0 0 1 7 0 0 0 0]
 [0 0 0 0 0 0 7 0 0]
 [0 0 3 0 5 0 0 0 6]
 [8 0 6 0 0 0 9 0 0]
 [0 0 0 0 0 9 0 0 1]
 [0 2 0 0 0 8 0 0 0]
 [5 0 2 9 0 0 8 0 0]
 [0 4 1 0 0 0 0 0 0]
 [0 6 0 0 0 4 3 0 0]]
Sudoku is consistent
Updating 2 at 2, 5
Updating 1 at 2, 6
Updating 8 at 4, 7
Updating 8 at 8, 2
Updating 9 at 1, 4
Updating 8 at 7, 4
Unable to solve the problem
[[0 0 0 1 7 0 0 0 0]
 [0 0 0 0 9 0 7 0 0]
 [0 0 3 0 5 2 1 0 6]
 [8 0 6 0 0 0 9 0 0]
 [0 0 0 0 0 9 0 8 1]
 [0 2 0 0 0 8 0 0 0]
 [5 0 2 9 0 0 8 0 0]
 [0 4 1 0 8 0 0 0 0]
 [0 6 8 0 0 4 3 0 0]]
Guessing between {3, 6} at 0, 5
[[0 0 0 1 7 0 0 0 0]
 [0 0 0 0 9 0 7 0 0]
 [0 0 3 0 5 2 1 0 6]
 [8 0 6 0 0 0 9 0 0]
 [0 0 0 0 0 9 0 8 1]
 [0 2 0 0 0 8 0 0 0]
 [5 0 2 9 0 0 8 0 0]
 [0 4 1 0 8 0 0 0 0]
 [0 6 8 0 0 4 3 0 0]]
Guessing 3 at 0, 5
Updating 6 at 1, 5
Updating 6 at 0, 0
Updating 2 at 1, 0
Updating 1 at 1, 1
Updating 1 at 5, 0
Updating 9 at 5, 2
Updating 7 at 4, 2
Updating 4 at 4, 0
Updating 3 at 7, 0
Updating 7 at 6, 1
Updating 1 at 6, 5
Updatin